/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module full_adder (
  input A,
  input B,
  input C_in,
  output Sum,
  output C_out
);
  assign Sum = (((A ^ B) & ~ C_in) | (((A & B) | (~ A & ~ B)) & C_in));
  assign C_out = ((A & B) | (A & C_in) | (B & C_in));
endmodule
