/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module comparador_2_bits (
  input A_0,
  input A_1,
  input B_0,
  input B_1,
  output AmayorB,
  output AmenorB,
  output AeqB
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  assign s2 = ~ A_0;
  assign s3 = ~ A_1;
  assign s0 = ~ B_0;
  assign s1 = ~ B_1;
  assign AmayorB = ((A_0 & s0 & s1) | (A_0 & A_1 & s0) | (A_1 & s1));
  assign AmenorB = ((s2 & (s3 | B_1) & B_0) | (s3 & B_1));
  assign AeqB = ((s2 & s3 & s0 & s1) | (A_0 & s3 & B_0 & s1) | (A_0 & A_1 & B_0 & B_1) | (s2 & A_1 & s0 & B_1));
endmodule
