/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Half_adder (
  input A,
  input B,
  output Sum,
  output carry
);
  assign Sum = (A ^ B);
  assign carry = (A & B);
endmodule
